// End-to-end interaction check for /pass3.html
import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true,
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage(); await page.setViewport({ width: 1200, height: 800 });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await page.goto(`${process.env.DEMO_URL || 'http://127.0.0.1:5180'}/pass3.html?auto=0`); await page.waitForFunction('window.appReady', { timeout: 180000 });
const st = () => page.evaluate(() => ({ az: +(app3.target.az * 180 / Math.PI).toFixed(1), el: +(app3.target.el * 180 / Math.PI).toFixed(1), size: +app3.target.size.toFixed(2), tx: +app3.target.tx.toFixed(2), tz: +app3.target.tz.toFixed(2), clock: document.getElementById('clock').value }));
const ok = (name, cond) => { console.log(cond ? 'PASS' : 'FAIL', name); if (!cond) process.exitCode = 1; };
const s0 = await st();
await page.mouse.move(600, 400); await page.mouse.down(); await page.mouse.move(800, 360, { steps: 6 }); await page.mouse.up();
const s1 = await st(); ok('drag orbits (az changes)', s1.az !== s0.az);
await page.mouse.wheel({ deltaY: -300 }); const s2 = await st(); ok('wheel zooms in', s2.size < s1.size);
await page.keyboard.down('Shift'); await page.mouse.move(600, 400); await page.mouse.down(); await page.mouse.move(700, 400, { steps: 4 }); await page.mouse.up(); await page.keyboard.up('Shift');
const s3 = await st(); ok('shift-drag pans', s3.tx !== s2.tx || s3.tz !== s2.tz);
await page.click('#presets button:nth-child(5)'); const s4 = await st(); ok('Night preset sets 22:00', s4.clock === '22:00');
await page.evaluate(() => { const h = document.getElementById('hour'); h.value = '12'; h.dispatchEvent(new Event('input', { bubbles: true })); });
ok('time slider updates clock', (await st()).clock === '12:00');
await page.click('#compare'); await page.waitForFunction('document.body.classList.contains("compare")', { timeout: 120000 });
ok('compare mode shows Pass 1 canvas', await page.evaluate(() => getComputedStyle(document.getElementById('p1-view')).display !== 'none'));
const same = await page.evaluate(() => { const a = document.getElementById('p3-view'), b = document.getElementById('p1-view'); return a.width === b.width && a.height === b.height; });
ok('both renderers share one resolution', same);
await page.click('#compare'); ok('compare toggles off', await page.evaluate(() => !document.body.classList.contains('compare')));
await page.click('#cycle'); await new Promise((r) => setTimeout(r, 1500)); await page.click('#cycle');
const dl = await page.evaluate(() => { const c = document.getElementById('p3-view'); return c.toDataURL('image/png').length; }); ok('canvas exports PNG', dl > 5000);
await page.setViewport({ width: 390, height: 780, deviceScaleFactor: 2 }); await new Promise((r) => setTimeout(r, 1500));
ok('mobile viewport has no horizontal scroll', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
const real = errs.filter((e) => !/favicon|toNonIndexed|GPU stall/.test(e));
ok(`no console/page errors (${real.length})`, real.length === 0); if (real.length) console.log(real);
await browser.close();
